### ISSUE TITLE
[BUG]: `serviceTerms` return value is different on Android

### ISSUE THREAD

**Issue by zmin9** [mym0404/react-native-kakao#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name, Version of @react-native-kakao/*

user / 1.4.5

### Version of react-native

0.73.4

### What os are you seeing the problem on?

Android

### What device types are you seeing the problem on?

Simulator

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Expo App

- [ ] I am using Expo

### What happened?

The return value of the `serviceTerms` function is different on ios and android.
* ios: `KakaoServiceTerms[]`
* android: `{ allowedServiceTerms :KakaoServiceTerms[] }`
   * different from the type

https://github.com/mym0404/react-native-kakao/blob/8c06cf3efbfddd30a78c9715d970e81a06f88402/packages/user/android/src/main/java/net/mjstudio/rnkakao/user/RNCKakaoUserModule.kt#L233-L238

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
Thank you for reporting
