### ISSUE TITLE
[FR]: iOS Static Framework, use_frameworks! support

### ISSUE THREAD

**Issue by galaxykhh** [mym0404/react-native-kakao#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

When using `use_frameworks!`, get a "RNCKakaoCore-Swift.h file not found" error during the build process.

### Environment
* Bare React Native with Expo Modules (50, 0.73.6)
* React Native Firebase installed.

### Podfile
```typescript
target 'picasso' do
  use_expo_modules!
  config = use_native_modules!

  # Firebase
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(

  ...

```

### Build output
```
❌  (node_modules/@react-native-kakao/core/ios/RNCKakaoCore.mm:2:9)

  1 | #import "RNCKakaoCore.h"
> 2 | #import "RNCKakaoCore-Swift.h"
    |         ^ 'RNCKakaoCore-Swift.h' file not found
  3 | 
  4 | @implementation RNCKakaoCore
  5 | 
```

### Describe the solution

Build success with use_frameworks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
Oh, pod with swift + objc always makes my working harder. I'll support static framework soon. thank you.

**Comment by mym0404** [comment]
`2.2.2` includes this patch.

**Comment by galaxykhh** [comment]
감사합니다~~~ Thanks !
