### ISSUE TITLE
[FEATURE]: Receive file share from KakaoTalk

### ISSUE THREAD

**Issue by QuocTA-Amela** [mym0404/react-native-kakao#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name, Version of @react-native-kakao/*

core, 1.0.0

### Version of react-native

0.74.5

### What os are you seeing the problem on?

Android, iOS

### What device types are you seeing the problem on?

Simulator, Physcial Device

### What architecture types of react native are you seeing the problem on?

Old Architecture(Bridge)

### Expo App

- [X] I am using Expo

### What happened?

I have a case like this.
My KakaoTalk want to share .txt file to my Expo app. Does this library support that? Thank you!

### Reproducible Sample Repository

No repository

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mym0404** [comment]
No you must check intent filter api.
